[application]
assets = "assets"
[web.app]
# HTML title tag content
title = "Moo's Profile"
# base_path = "/"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
# style = ["assets/main.css"]
style = []

# Additional static files
static = [
    "assets/bg_profile.jpg",
    "assets/profile.jpg",
]

# preload = true
# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
